package fold

import (
	"bytes"
	"fmt"
	"path"
	"strings"
	"text/template"
)

// GenerateMain produces Go source for a main.go that builds the CLI
// from the manifest. The generated code imports the module cmd package
// and calls its Execute() function.
func GenerateMain(m *Manifest, reg ModuleRegistry) ([]byte, error) {
	ctx, err := buildTemplateContext(m, reg)
	if err != nil {
		return nil, err
	}

	tmpl, err := template.New("main").Parse(mainTemplate)
	if err != nil {
		return nil, fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, ctx); err != nil {
		return nil, fmt.Errorf("execute template: %w", err)
	}

	return buf.Bytes(), nil
}

type templateContext struct {
	Name       string
	Imports    []importEntry
	CmdImport  string
	CmdAlias   string
	HasVersion bool
}

type importEntry struct {
	Alias string
	Path  string
}

func buildTemplateContext(m *Manifest, reg ModuleRegistry) (*templateContext, error) {
	ctx := &templateContext{
		Name:       m.Name,
		HasVersion: m.Version != "",
	}

	seen := map[string]bool{}

	for _, imp := range m.Imports {
		goPath, err := reg.ResolveFQCN(imp)
		if err != nil {
			return nil, fmt.Errorf("resolve import %q: %w", imp, err)
		}
		if seen[goPath] {
			continue
		}
		seen[goPath] = true

		alias := safeAlias(goPath)
		cmdPath := goPath + "/cmd"

		if !seen[cmdPath] {
			ctx.CmdImport = cmdPath
			ctx.CmdAlias = alias + "cmd"
			seen[cmdPath] = true
		}
	}

	if ctx.CmdImport == "" {
		return nil, fmt.Errorf("manifest must import at least one module with a cmd/ package")
	}

	return ctx, nil
}

func safeAlias(importPath string) string {
	base := path.Base(importPath)
	base = strings.ReplaceAll(base, "-", "")
	return base
}

var mainTemplate = `// Code generated by origami fold. DO NOT EDIT.
package main

import {{ .CmdAlias }} "{{ .CmdImport }}"

func main() { {{ .CmdAlias }}.Execute() }
`
