package fold

import (
	"bytes"
	"fmt"
	"path"
	"sort"
	"strings"
	"text/template"
)

// GenerateMain produces Go source for a main.go that builds the CLI
// from the manifest. The generated code imports the module cmd package
// and calls its Execute() function.
func GenerateMain(m *Manifest, reg ModuleRegistry) ([]byte, error) {
	ctx, err := buildTemplateContext(m, reg)
	if err != nil {
		return nil, err
	}

	tmpl, err := template.New("main").Parse(mainTemplate)
	if err != nil {
		return nil, fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, ctx); err != nil {
		return nil, fmt.Errorf("execute template: %w", err)
	}

	return buf.Bytes(), nil
}

type templateContext struct {
	Name       string
	Imports    []importEntry
	CmdImport  string
	CmdAlias   string
	HasVersion bool
	Bindings   []bindingEntry
}

type importEntry struct {
	Alias string
	Path  string
}

type bindingEntry struct {
	Socket      string
	OptionFunc  string
	FactoryFunc string
	ConnAlias   string
}

func buildTemplateContext(m *Manifest, reg ModuleRegistry) (*templateContext, error) {
	ctx := &templateContext{
		Name:       m.Name,
		HasVersion: m.Version != "",
	}

	seen := map[string]bool{}

	for _, imp := range m.Imports {
		goPath, err := reg.ResolveFQCN(imp)
		if err != nil {
			return nil, fmt.Errorf("resolve import %q: %w", imp, err)
		}
		if seen[goPath] {
			continue
		}
		seen[goPath] = true

		alias := safeAlias(goPath)
		cmdPath := goPath + "/cmd"

		if !seen[cmdPath] {
			ctx.CmdImport = cmdPath
			ctx.CmdAlias = alias + "cmd"
			seen[cmdPath] = true
		}
	}

	if ctx.CmdImport == "" {
		return nil, fmt.Errorf("manifest must import at least one module with a cmd/ package")
	}

	if len(m.Bindings) > 0 {
		bindings, err := resolveBindings(m.Bindings, reg, seen, ctx)
		if err != nil {
			return nil, err
		}
		ctx.Bindings = bindings
	}

	return ctx, nil
}

// socketOptionMap maps socket names to the cmd.With* function that satisfies
// them. This is the glue between component.yaml socket declarations and the
// generated main.go.
var socketOptionMap = map[string]string{
	"source":          "WithSourceFactory",
	"store":           "WithStoreFactory",
	"pusher":          "WithPusherFactory",
	"launch_fetcher":  "WithLaunchFetcherFactory",
}

func resolveBindings(bindings map[string]string, reg ModuleRegistry, seen map[string]bool, ctx *templateContext) ([]bindingEntry, error) {
	sockets := make([]string, 0, len(bindings))
	for s := range bindings {
		sockets = append(sockets, s)
	}
	sort.Strings(sockets)

	var entries []bindingEntry
	for _, socket := range sockets {
		connFQCN := bindings[socket]
		goPath, err := reg.ResolveFQCN(connFQCN)
		if err != nil {
			return nil, fmt.Errorf("resolve binding %q -> %q: %w", socket, connFQCN, err)
		}

		alias := safeAlias(goPath)
		if !seen[goPath] {
			seen[goPath] = true
			ctx.Imports = append(ctx.Imports, importEntry{Alias: alias, Path: goPath})
		}

		optFunc, ok := socketOptionMap[socket]
		if !ok {
			known := make([]string, 0, len(socketOptionMap))
			for k := range socketOptionMap {
				known = append(known, k)
			}
			sort.Strings(known)
			return nil, fmt.Errorf("unknown socket %q in bindings (known: %s)", socket, strings.Join(known, ", "))
		}

		factory := lookupFactory(socket, goPath, reg)

		entries = append(entries, bindingEntry{
			Socket:      socket,
			OptionFunc:  optFunc,
			FactoryFunc: factory,
			ConnAlias:   alias,
		})
	}
	return entries, nil
}

func lookupFactory(socket, goPath string, reg ModuleRegistry) string {
	switch socket {
	case "source":
		return "NewSourceAdapter"
	case "store":
		return "NewStore"
	case "pusher":
		return "NewDefectPusher"
	case "launch_fetcher":
		return "NewLaunchFetcher"
	default:
		return "New"
	}
}

func safeAlias(importPath string) string {
	base := path.Base(importPath)
	base = strings.ReplaceAll(base, "-", "")
	return base
}

var mainTemplate = `// Code generated by origami fold. DO NOT EDIT.
package main

import (
	{{ .CmdAlias }} "{{ .CmdImport }}"
{{- range .Imports }}
	{{ .Alias }} "{{ .Path }}"
{{- end }}
)

func main() {
{{- if .Bindings }}
	{{ .CmdAlias }}.Apply(
{{- range .Bindings }}
		{{ $.CmdAlias }}.{{ .OptionFunc }}({{ .ConnAlias }}.{{ .FactoryFunc }}),
{{- end }}
	)
{{- end }}
	{{ .CmdAlias }}.Execute()
}
`
