package fold

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"text/template"
)

// GenerateDomainServe produces Go source for a domain-serve binary that
// embeds domain files and serves them over MCP via domainserve.New().
// Supports both legacy (embed: directory) and assets (keyed file map) modes.
func GenerateDomainServe(m *Manifest) ([]byte, error) {
	if m.DomainServe == nil {
		return nil, fmt.Errorf("manifest has no domain_serve section")
	}
	ds := m.DomainServe
	if ds.Embed == "" && ds.Assets == nil {
		return nil, fmt.Errorf("domain_serve: one of embed or assets is required")
	}

	port := ds.Port
	if port == 0 {
		port = 9300
	}

	ctx := domainServeContext{
		Name:    m.Name,
		Version: m.Version,
		Port:    port,
	}

	if ds.Embed != "" {
		ctx.EmbedDir = strings.TrimRight(ds.Embed, "/")
	} else {
		ctx.EmbedPaths = ds.Assets.AllPaths()
		ctx.AssetSections = ds.Assets.Sections()
		ctx.AssetFiles = ds.Assets.ScalarFiles()
	}

	tmpl, err := template.New("domain-serve").Funcs(template.FuncMap{
		"goStringMap": goStringMap,
		"goNestedMap": goNestedMap,
	}).Parse(domainServeTemplate)
	if err != nil {
		return nil, fmt.Errorf("parse domain-serve template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, ctx); err != nil {
		return nil, fmt.Errorf("execute domain-serve template: %w", err)
	}

	return buf.Bytes(), nil
}

type domainServeContext struct {
	Name          string
	Version       string
	Port          int
	EmbedDir      string                       // legacy mode
	EmbedPaths    []string                     // assets mode: sorted file list
	AssetSections map[string]map[string]string // assets mode: section -> key -> path
	AssetFiles    map[string]string            // assets mode: singleton files
}

func (c domainServeContext) HasAssets() bool {
	return len(c.EmbedPaths) > 0
}

// goStringMap formats map[string]string as a Go literal.
func goStringMap(m map[string]string) string {
	if len(m) == 0 {
		return "nil"
	}
	var b strings.Builder
	b.WriteString("map[string]string{")
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(&b, "%q: %q, ", k, m[k])
	}
	b.WriteString("}")
	return b.String()
}

// goNestedMap formats map[string]map[string]string as a Go literal.
func goNestedMap(m map[string]map[string]string) string {
	if len(m) == 0 {
		return "nil"
	}
	var b strings.Builder
	b.WriteString("map[string]map[string]string{\n")
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(&b, "\t\t\t%q: %s,\n", k, goStringMap(m[k]))
	}
	b.WriteString("\t\t}")
	return b.String()
}

var domainServeTemplate = `// Code generated by origami fold. DO NOT EDIT.
package main

import (
	"embed"
	"fmt"
	"net/http"
	"os"

	"github.com/dpopsuev/origami/domainserve"
)

{{ if .HasAssets -}}
{{ range .EmbedPaths -}}
//go:embed {{ . }}
{{ end -}}
{{ else -}}
//go:embed {{ .EmbedDir }}
{{ end -}}
var domainData embed.FS

func main() {
	handler := domainserve.New(domainData, domainserve.Config{
		Name:    {{ printf "%q" .Name }},
		Version: {{ printf "%q" .Version }},
{{ if .HasAssets -}}
		Assets: &domainserve.AssetIndex{
			Sections: {{ goNestedMap .AssetSections }},
			Files:    {{ goStringMap .AssetFiles }},
		},
{{ end -}}
	})
	addr := fmt.Sprintf(":%d", {{ .Port }})
	fmt.Fprintf(os.Stderr, "domain-serve listening on %s\n", addr)
	if err := http.ListenAndServe(addr, handler); err != nil {
		fmt.Fprintf(os.Stderr, "domain-serve: %v\n", err)
		os.Exit(1)
	}
}
`
