package fold

import (
	"bytes"
	"fmt"
	"text/template"
)

// GenerateDockerfile produces a Dockerfile for a schematic that has a serve
// entrypoint declared in its component.yaml.
func GenerateDockerfile(schematicName, servePath, goVersion string) ([]byte, error) {
	if servePath == "" {
		return nil, fmt.Errorf("schematic %q has no serve entrypoint", schematicName)
	}
	if goVersion == "" {
		goVersion = "1.24"
	}

	tmpl, err := template.New("dockerfile").Parse(dockerfileTemplate)
	if err != nil {
		return nil, fmt.Errorf("parse dockerfile template: %w", err)
	}

	ctx := dockerfileContext{
		GoVersion:     goVersion,
		SchematicName: schematicName,
		ServePath:     servePath,
		Port:          9100,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, ctx); err != nil {
		return nil, fmt.Errorf("execute dockerfile template: %w", err)
	}

	return buf.Bytes(), nil
}

type dockerfileContext struct {
	GoVersion     string
	SchematicName string
	ServePath     string
	Port          int
}

var dockerfileTemplate = `# Generated by origami fold --container. DO NOT EDIT.
FROM golang:{{ .GoVersion }} AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /{{ .SchematicName }} ./{{ .ServePath }}/

FROM gcr.io/distroless/static
COPY --from=builder /{{ .SchematicName }} /{{ .SchematicName }}
ENTRYPOINT ["/{{ .SchematicName }}"]
EXPOSE {{ .Port }}
`
